### ISSUE TITLE
Any plan to support Bitflyer and Coincheck?

### ISSUE THREAD

**Issue by winwish** [timmolter/XChange#1887] opened 2017-11-13 12:52 UTC

**Comment by timmolter** [comment] 2017-11-13 12:58
no plans yet.

**Comment by lukaszaoralek** [comment] 2017-11-15 15:46
Bitflyer streaming support https://github.com/bitrich-info/xchange-stream/pull/27

**Comment by Unbr8kbal** [comment] 2017-11-17 07:05
@winwish Would you be willing to donate a bounty?

**Comment by winwish** [comment] 2017-11-22 09:54
After I receive the postcard from them to pass verification, I think I can donate some or share with someone with the same needs.

**Comment by joggerjoel** [comment] 2017-11-22 10:54
bitmex too

**Comment by lukaszaoralek** [comment] 2017-11-22 15:29
If you are only interested in public (market data) API, the xchange-stream (websocket) supports Bitflyer and Bitmex now

**Comment by cristianlucaci** [comment] 2017-12-19 12:13
hey, does anyone has any updates on Bitflyer implementation? I intended to start the implementation, but I have difficulties enabling the API keys.

**Comment by timmolter** [comment] 2018-01-02 09:32
closing as duplicate of:

* https://github.com/timmolter/XChange/issues/1264
* https://github.com/timmolter/XChange/issues/1959

**Closed by timmolter** 2018-01-02 09:32 UTC
Labels: Feature Request, New Exchange
