### ISSUE TITLE
[50 mBTC Bounty] Bitmex implementation

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1747] opened 2017-09-04 05:44 UTC
HI, Was thinking about implementing bitmex exchange and wondered if anyone had started work on this or intrested in collabrating.

**Comment by jheusser** [comment] 2017-09-04 08:07
Check https://github.com/timmolter/XChange/issues/1215 opened by .. you 🤣

**Comment by timmolter** [comment] 2017-10-13 11:58
Maybe offer a bounty?

**Comment by makarid** [comment] 2017-10-16 22:19
Hello,i can offer a bountry for this.Can you please tell me how much it is good and how can i do that.Thanks

**Comment by timmolter** [comment] 2017-10-17 08:20
@makarid To offer a bounty, just write a new comment on this issue how much you are offering. I will update the title with the bounty amount and add the bounty tag. When complete (I accept the pull request), the implementor will post his/her BTC address, and you can send the funds. If the implementor wants, I can hold the funds in escrow.

**Comment by timmolter** [comment] 2017-10-17 08:21
A good amount to start would be around 50 mBTC, I think.

**Comment by makarid** [comment] 2017-10-17 12:46
Thanks a lot for your reply.I offer 50mBTC if someone can implement the bitmex exchange.I am mostly interested on the XBTUSD perpetual swap contract,so maybe this is much more simpler.I am waiting for your responses,thanks a lot!

**Comment by makarid** [comment] 2017-10-17 13:31
I would like to ask one thing.Is it possible the orderbook feed to be implemented with websocket?I read on the documentation of the bitmex that they only use websocket for data feeds and not for actions like open/cancel trades.I do not know the technicalities about that.Maybe i am wrong.Thanks.

**Comment by timmolter** [comment] 2017-10-17 13:48
See our README about streaming APIs.

**Comment by makarid** [comment] 2017-10-17 13:58
Can i transfer the same bounty to the xchange-stream in order the implementation to be made for websocket and not for this project?Thanks.

**Comment by timmolter** [comment] 2017-10-17 14:04
Yes, go for it. Just close this issue and open a new one on their issues page.

**Comment by timmolter** [comment] 2017-10-17 14:04
No wait, leave this open. I'll just remove the bounty if you tell me to do so.

**Comment by makarid** [comment] 2017-10-17 14:05
Thanks a lot man! Please remove the bounty and i will make a new one on the stream xchange.

**Comment by makarid** [comment] 2017-10-17 21:07
Hi,i would like to reopen the bounty of 50mBTC for implementing Bitmex exchange.I read in the API documentation that Bitmex supports  HTTP Keep-Alive and have the same latency as websocket without using websockets.So i am waiting for your responses.Thanks a lot!

**Comment by timmolter** [comment] 2017-10-18 06:57
ok, reopened.

**Comment by lukaszaoralek** [comment] 2017-11-13 19:27
@makarid
I've just written Bitmex streaming (websocket) as a module of the xchange-streaming project. I just made PR request there (https://github.com/bitrich-info/xchange-stream/pull/24), but if you want you can test it now https://github.com/lukaszaoralek/xchange-stream/tree/bitmex

I don't complain for bounty if you like it :)

**Comment by makarid** [comment] 2017-11-14 17:56
Hello lukas,
yes ofcourse i don't have a problem to give you the bounty.I just need to test it first because i don't have any experience with websocket.Thanks!

**Comment by lukaszaoralek** [comment] 2017-11-14 18:05
Yep, I expect you will test it first and I can fix potential issues if there occur ...let me know here or in xchange-stream after testing ...the bitmex module has been merged with develop branch in xchange-stream

**Comment by makarid** [comment] 2017-11-17 10:37
Hi lukas,
i am sorry but i cannot test it because i don't know how to connect to bitmex.I have use the same method as the Xchange example provides changing the Exchange with StreamingExchange,but i cannot connect.Could you please update the examples on README file,for how to connect to the exchange and how to view ,for example, bid offers of the orderbook or something?The readme file of the Xchange-stream is too limited and i cannot understand how it works.I am sorry for the newbies problem that i have but i am not a pro.Thank you so much!

**Comment by lukaszaoralek** [comment] 2017-11-18 09:51
@makarid 
Hi makarid, no problem ...look at the code [BitmexManualExample](https://github.com/bitrich-info/xchange-stream/blob/develop/xchange-bitmex/src/test/java/info/bitrich/xchangestream/bitmex/BitmexManualExample.java) located at the test folder...it's complete example how can you obtain orderbook snapshots, trades and ticker events

**Comment by makarid** [comment] 2017-11-18 10:21
Hi lukas,
thank you so much for these examples!!!Can you please also tell me what else do i need to set in order to connect to bitmex api?I have write the following method and i call it when i need to create an bitmexExchange:

    private static StreamingExchange bitmexApiConnection(){
        final String bitmexApiKey = "****";
        final String bitmexApiSecret = "****";

        StreamingExchange bitmexExchange = StreamingExchangeFactory.INSTANCE.createExchange(BitmexStreamingExchange.class.getName());

        bitmexExchange.getExchangeSpecification().setApiKey(bitmexApiKey);
        bitmexExchange.getExchangeSpecification().setSecretKey(bitmexApiSecret);
        bitmexExchange.getExchangeSpecification().setExchangeName("Bitmex");
        bitmexExchange.applySpecification(bitmexExchange.getExchangeSpecification());

        return bitmexExchange;
    }

but 2 warnings and 1 error occurs.Do i need to add something else.Thanks a lot! 

The error log is this:

253 [main] WARN com.Test.BitmexStreamingExchange - No "exchange name" found in the ExchangeSpecification. The name is used to load the meta data file from the classpath and may lead to unexpected results.
269 [main] WARN com.Test.BitmexStreamingExchange - An exception occured while loading the metadata file from the file system. This is just a warning and can be ignored, but it may lead to unexpected results, so it's better to address it.
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4134)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at org.knowm.xchange.BaseExchange.loadMetaData(BaseExchange.java:137)
	at org.knowm.xchange.BaseExchange.loadExchangeMetaData(BaseExchange.java:128)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:96)
	at com.Test.Main.bitmexApiConnection(Main.java:699)
	at com.Test.Main.main(Main.java:57)
Exception in thread "main" java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.connect(NettyStreamingService.java:53)
	at com.Test.BitmexStreamingExchange.connect(BitmexStreamingExchange.java:30)
	at com.Test.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by lukaszaoralek** [comment] 2017-11-18 10:37
@makarid 
The streaming API supports only streaming public market data events. The public channels don't need authentication (like call setApiKey or setSecretKey). If you want also to use trade API, try to use REST API from the "standard" XChange library.

**Comment by makarid** [comment] 2017-11-18 10:44
I am sorry but i am little confused.So the streamingAPI only displays public data info and doesn't do trades.How can i place trades if there isn't bitmex implementation on "standard" Xchange library?Thanks!

**Comment by makarid** [comment] 2017-11-18 10:50
Also,even if i copy paste the code from the BitmexExampleFile.I get the following warning/error:

319 [main] WARN com.Test.BitmexStreamingExchange - No "exchange name" found in the ExchangeSpecification. The name is used to load the meta data file from the classpath and may lead to unexpected results.
Exception in thread "main" java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.connect(NettyStreamingService.java:53)
	at com.Test.BitmexStreamingExchange.connect(BitmexStreamingExchange.java:30)
	at com.Test.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by lukaszaoralek** [comment] 2017-11-18 11:28
@makarid 
Exception in thread "main" java.lang.NoClassDefFoundError: org/reactivestreams/Publisher ...it says your jvm can't find the class Publisher. Please try this way:
```
$ git clone https://github.com/bitrich-info/xchange-stream.git
$ cd xchange-stream
$ mvn -pl xchange-bitmex -Dexec.mainClass=info.bitrich.xchangestream.bitmex.BitmexManualExample -Dexec.classpathScope=test test-compile exec:java
```

**Comment by makarid** [comment] 2017-11-18 11:57
God bless you man! Thanks a lot,it worked! What about trades? Can i execute trades? Thank you so much!

**Comment by lukaszaoralek** [comment] 2017-11-18 12:17
@makarid 
As I mentioned above the xchange-stream doesn't support the Trade API. You can consider this solution:
> If you want also to use trade API, try to use REST API from the "standard" XChange library.

**Comment by makarid** [comment] 2017-11-18 12:57
Can i send you an email?

**Comment by lukaszaoralek** [comment] 2017-11-18 14:47
sure, check my github profile

**Closed** 2017-12-06 13:28 UTC
Labels: Bounty, Feature Request

**Comment by robinersek** [comment] 2017-12-09 21:47
Hi all,

This discussion has been very useful to me, it was a great help to get the data streams running, thanks a lot!

I had lots of troubles with the REST requests though, but I finally got all request types running after a few days of head scratching & banging against the wall (it was especially difficult for me to calculate the nonce and signature properly, then I got stuck with feeding the data to the requests... etc.).

So since I got the initial information and code from this discussion, I decided to post my Java code which will enable anyone reading this to run test or live REST request queries of all 4 types (GET, PUT, POST, DELETE), so basically it can be used to run any request available in the BitMEX REST API in a simplified way.

I was working in a Maven project, so first of all you'll need these dependencies added to your project:

[dependencies.txt](https://github.com/timmolter/XChange/files/1545130/dependencies.txt)

And here's the code to run requests (I left my notes and resource links in the code, since it provides useful information + I renamed the .java to .txt to be able to upload it here):

[BitmexManualExample.txt](https://github.com/timmolter/XChange/files/1545135/BitmexManualExample.txt)

To run a simple test, you simply need to:
- add the dependencies to you pom.xml file in your Maven project (or download the JAR files listed in the dependencies and add to your Java project)
- Go to Test BitMEX platform, register an account (free) and create your API key here: https://testnet.bitmex.com/app/apiKeys
- Finally fill in your API credentials into the above code, into the 'Test API keys' section (testUsername, testApiKey, testApiSecret)
- Hit Run, and see that it starts getting the stream data and submitting Market & Limit orders, and deletes pending (Limit) orders, etc. (Market order will stay live, so check your Positions tab!)

If you received no errors (hopefully), then you can start playing with the requests, the for main request to call are:
- executeGETRequest(path) -- to receive data from the exchange
- executePOSTRequest(path, data) -- to post data, like creating an order
- executePUTRequest(path, data) -- to put data, like changing an order price or size, so it's in comments by default, since it requires an existing order id
- executeDELETERequest(path, data) -- to delete an order, so it's in comments by default, since it requires an existing order id

Please note:
Firstly, 'path' is not the full URL, but the end of the url, which is written after bitmex.com or testnet.bitmex.com
So path is basically the REST API call, for details check BitMEX REST API Explorer: https://www.bitmex.com/api/explorer/
Secondly, I prefer using the HashMap approach to provide data in the 'data' field (for PUT, POST and DELETE requests) and I suggest you use that too, since it makes it much easier than using a URL encoder to generate a data string:

_HashMap<String, String> hmap = new HashMap<String, String>();
hmap.put("symbol", "XBTUSD");
hmap.put("orderQty", "1"); // Long order: amount is positive. To execute a SHORT order, use a negative number: hmap.put("orderQty", "-1");
hmap.put("ordType", "Market");
executePOSTRequest("/api/v1/order", convertHmapToData(hmap));_

But if you want to go that way, you can totally do that too, since there are examples like that in the code, just check the commented requests, like this one (it's the same Market order for 1 USD as above, in the HashMap script):

_//executePOSTRequest("/api/v1/order", "symbol=XBTUSD&orderQty=1&ordType=Market");_

Basically, I tried to come up with an interface which can be used to run any REST API calls, that's why I included all 4 types of requests (GET, POST, PUT, DELETE) which can be found in the BitMEX REST API interface. Now all you need to do is fill the data into the HashMap and make the call (the REST API Explorer - https://www.bitmex.com/api/explorer - is extremely useful to check how to fill in the data and what results to expect).

So once you figured out all the calls you need for your Java BitMEX trading bot and tested them on the test system, all you need to do is:
- register into the live bitmex system at bitmex.com
- create your API keys
- set the live API credentials in the code
- turn it on by setting isTest boolean to 'false'

and you can start your bot to trade for you day and night!

Hope you guys find that helpful!

**Comment by makarid** [comment] 2017-12-15 09:44
Hi robinersek,
thanks you so much for your post! I would like to ask you one thing about the data that these lines throwing:

// Order Book streams
		exchange.getStreamingMarketDataService().getOrderBook(xbtUsd).subscribe(orderBook -> {
		  System.out.println("First ask: " + orderBook.getAsks().get(0));
		  System.out.println("First bid: " + orderBook.getBids().get(0));
		}, throwable -> new Exception("getOrderBook error!"));

When i run it i get an infinite loop throwing these 2 lines with live price feeds.How can i get these outputs 1 time only and make some computations?
Thanks a lot!

**Comment by robinersek** [comment] 2017-12-15 10:10
Hi,
this is a subscription to the stream, so as the feed comes in, you do the action what you put between the { } brackets.
So if you want to evaluate each price quote as they come in, you simply need to change the System.out... lines to your script, or add additional script to it, like this:

// Order Book streams
exchange.getStreamingMarketDataService().getOrderBook(xbtUsd).subscribe(orderBook -> {
[add any java code here...]
}, throwable -> new Exception("getOrderBook error!"));

If you want to exit after the first incoming price quote, you can simply use the java.lang.System.exit() in there, like this:

// Order Book streams
exchange.getStreamingMarketDataService().getOrderBook(xbtUsd).subscribe(orderBook -> {
[add any java code here...]
System.exit(0);
}, throwable -> new Exception("getOrderBook error!"));

I hope that helps!

**Comment by makarid** [comment] 2017-12-15 20:23
Thanks a lot for your help robinersek!!!

**Comment by cristianlucaci** [comment] 2017-12-18 11:46
hi @robinersek , any chance you can implement Bitmex as a new module in XChange, according to https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices ?

**Comment by robinersek** [comment] 2017-12-18 20:16
Hi, I'd love to contribute. Unfortunately, I do not have any spare time at the moment. If anyone is willing to take this on, I am happy to help in any way I can. The code I uploaded does work fine - I actually finished my fully working bot and have it running on BitMEX right now -, so if anyone has the time to do the XChange implementation I am here to help and discuss any issues.

**Comment by cristianlucaci** [comment] 2017-12-19 10:09
@timmolter I would like to create a PR for Bitmex implementation, but please be advised its only a partial implementation. Only a small part of their API is implemented, mainly the Raw Margin/Account/Wallet operations. I will most probably implement the trading API sometime in the future (no ETA yet), depending on my requirements. Are you ok with this approach?

**Comment by timmolter** [comment] 2017-12-19 13:44
Even a partial implementation is fine. You or someone later can always build upon it. Thanks!
