### ISSUE TITLE
Support bitFlyer

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#1410] opened 2017-03-24 08:32 UTC
A lot of volume, free trading, good API: https://lightning.bitflyer.jp/docs?lang=en

**Comment by lukaszaoralek** [comment] 2017-11-15 15:46
@jheusser 
I've just written PR with bitflyer websocket support https://github.com/bitrich-info/xchange-stream/pull/27. You can try/test it if it's still actual for you

**Comment by timmolter** [comment] 2018-01-02 09:30
Closing as duplicate of: <https://github.com/timmolter/XChange/issues/1959>

**Closed by timmolter** 2018-01-02 09:30 UTC
Labels: Feature Request
