### ISSUE TITLE
Binance Example

### ISSUE THREAD

**Issue by axpence** [timmolter/XChange#1993] opened 2017-12-17 11:37 UTC
Hi folks,
I was able to add `xchange-binance` to my project, however I am having trouble initializing the exchange. I don't see an example in the `examples/` and have tried two different methods:

```
//BINANCE
    public static Exchange createBinanceExchange(){
        ExchangeSpecification exSpec = new BinanceExchange().getDefaultExchangeSpecification();
        exSpec.setUserName("myemail@gmail.com");
        exSpec.setApiKey("API_KEY_HERE");
        exSpec.setSecretKey("SECRET+HERE");
        return ExchangeFactory.INSTANCE.createExchange(exSpec);




    }
    public static Exchange createBinanceExchange2() {

        Exchange bfx = ExchangeFactory.INSTANCE.createExchange(BinanceExchange.class.getName());
        ExchangeSpecification bfxSpec = bfx.getDefaultExchangeSpecification();
        bfxSpec.setApiKey("API_KEY+HERE");
        bfxSpec.setSecretKey("SECRET+HERE");
        bfx.applySpecification(bfxSpec);
        return bfx;
    }


```

Anybody have a Binance example they'd be willing to share? thanks!

**Comment by jcuypers** [comment] 2017-12-17 17:04
Just try to get the basic exchange information  and proceed from there.  
You could use a function like below to get a list of currencypairs of an exchange
classname for binance should be  :  org.knowm.xchange.binance.BinanceExchange

If this works:  just take any basic account/trade/market example of any other exchange and transform it. 
It should be straightforward to do.  good luck 

I've tested it, it works.  but I dont have an account on Binance to test further

public static List<CurrencyPair> getExchangeCurrencyPairs(String Classname)
    {
        List<CurrencyPair> currencyPairList = null;

        Exchange exch = null;

        try {
            exch = ExchangeFactory.INSTANCE.createExchange(Classname);
            currencyPairList = exch.getExchangeSymbols();
        }
        catch (NonceException e) {
            System.out.println("Nonce exception...");
        }
        catch (ExchangeException e) {
            System.out.println("Exchange exception...");
        }
        catch (Exception e) {
            System.out.println("ok we have an issue...");
        }
        return currencyPairList;
    }

**Comment by axpence** [comment] 2017-12-17 17:43
Thanks, @jcuypers for your comment. I agree the first step is to try and get exchange information. 

I attempted to obtain the `CurrencyPair`s using your method, however, I am getting the `Exception`. Here is how I am calling the code:

``` List<CurrencyPair> currencyPairs = getExchangeCurrencyPairs(org.knowm.xchange.binance.BinanceExchange.class.getName());```

Here is the terminal output:
```
objc[85819]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x1079254c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1079b14e0). One of the two will be used. Which one is undefined.
09:43:24.805 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
09:43:24.809 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
09:43:25.457 [default] [main] DEBUG o.k.xchange.binance.BinanceExchange - ExchangeMetaData [currencyPairs=null, currencies=null, publicRateLimits=null, privateRateLimits=null, shareRateLimits=false] 
09:43:25.500 [default] [main] INFO  o.k.xchange.binance.BinanceExchange - Calling Remote Init... 
ok we have an issue...
```

Am I missing something?

**Comment by KevinJannis** [comment] 2017-12-18 07:25
@jcuypers,

I am having the same issue as well.
It seems the error is caused in `BaseExchange.getExchangeMetaData()`, which returns `null`:
```

  @Override
  public List<CurrencyPair> getExchangeSymbols() {
    return new ArrayList<>(getExchangeMetaData().getCurrencyPairs().keySet());
  }
```

I do not use a metadata json file.

K.

**Comment by KevinJannis** [comment] 2017-12-18 07:32
@timmolter,

It seems this issue is fixed in the `develop` branch. When is a new release expected?

K.

**Comment by jcuypers** [comment] 2017-12-18 08:39
Yes 4.2.3 works fine.
Seems strange naming to me : [main] DEBUG o.k.xchange.binance.BinanceExchange - ExchangeMetaData

**Comment by timmolter** [comment] 2017-12-18 09:19
@KevinJannis https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions

**Comment by KevinJannis** [comment] 2017-12-18 19:01
@jcuypers,

Can you create a new instance of the BinanceExchange? I can not seem to get it working. Are you using a metadata json file? Can you post that file if you use one?

K.

**Comment by jcuypers** [comment] 2017-12-19 07:52
@KevinJannis Yes. Working without a json file. nothing special

**Comment by KevinJannis** [comment] 2017-12-19 18:31
@jcuypers,

Can you fetch the exchange symbols? I keep getting the following error:

`org.knowm.xchange.binance.dto.BinanceException: -1021: Timestamp for this request is outside of the recvWindow.`

**Comment by cymp** [comment] 2017-12-19 19:01
This is because your local system time is not close enough to the binance server one. Compare your server local time to https://api.binance.com/api/v1/time, and adjust your recvWindow size, or your local server time.

**Comment by KevinJannis** [comment] 2017-12-19 19:33
@cymp,
I do not think it is not possible to set the recvWindow in this library?

**Comment by cymp** [comment] 2017-12-19 22:43
Last time I checked, it was hardcoded indeed. Maybe needs a PR.

**Comment by KevinJannis** [comment] 2017-12-20 08:28
@cymp,
As requested:
https://github.com/timmolter/XChange/pull/2009

**Comment by assaad** [comment] 2017-12-20 16:32
I am having a related issue: 

17:31:40.814 [default] [main] WARN  o.k.xchange.binance.BinanceExchange - An exception occurred while loading the metadata java.lang.NullPointerException: null
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:61)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:85)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:42)
	at lu.btcexplore.ExchangeTest.getSupportedCurrency(ExchangeTest.java:53)
	at lu.btcexplore.ExchangeTest.main(ExchangeTest.java:24)

**Comment by ortschun** [comment] 2017-12-25 14:05
@KevinJannis any plans to release this fix?

**Comment by KevinJannis** [comment] 2017-12-25 19:48
@ortschun https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions

**Comment by jcuypers** [comment] 2017-12-31 12:29
Now i started having issues with Binance... :-) 

 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                                                                               at org.knowm.xchange.utils.AuthUtils.getSecretProperties(AuthUtils.java:63)
                                                                               at org.knowm.xchange.utils.AuthUtils.setApiAndSecretKey(AuthUtils.java:41)
                                                                               at org.knowm.xchange.binance.BinanceExchange.getDefaultExchangeSpecification(BinanceExchange.java:47)
                                                                               at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:80)
                                                                               at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:42)


Any clue?

**Comment by timmolter** [comment] 2018-01-02 09:11
Seems like a classpath issue. Are you using maven?

**Closed by timmolter** 2018-01-02 09:11 UTC

**Comment by jcuypers** [comment] 2018-01-03 11:23
Yes, I link to the dev repository
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
and then I use them in gradle
    implementation 'org.knowm.xchange:xchange-core:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-bitfinex:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-poloniex:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-hitbtc:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-bittrex:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-bitstamp:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-kraken:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-coinbase:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-gdax:4.3.2-SNAPSHOT'
    implementation 'org.knowm.xchange:xchange-binance:4.3.2-SNAPSHOT'

I was just surprised since it stopped working without any changes.  I just used binance for getting available symbols back.  removed it for now.

**Comment by ZorgeR** [comment] 2018-01-20 01:09
java.nio.file.Path exception on Binance library 4.3.2
