### ISSUE TITLE
Request for support for Bithumb exchange

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2050] opened 2017-12-27 02:38 UTC
Here's a link to their API documentation (https://www.bithumb.com/u1/US127)

I'm also attaching their Java sample which demonstrates their usage (sample also available from their site). 

[Bithumb_20150824_RESTFulAPI-java.zip](https://github.com/timmolter/XChange/files/1588220/Bithumb_20150824_RESTFulAPI-java.zip)

**Comment by timmolter** [comment] 2018-01-02 09:19
Closing as duplicate of: <https://github.com/timmolter/XChange/issues/1871>

**Closed by timmolter** 2018-01-02 09:19 UTC
Labels: Feature Request, New Exchange
