### ISSUE TITLE
UndeclaredThrowableException @ Poloniex

### ISSUE THREAD

**Issue by andre77** [timmolter/XChange#1211] opened 2016-03-15 05:24 UTC
i get a lot of exceptions of type UndeclaredThrowableException

not completely sure, but i guess, the reason could be, that some motheds in the interface
com.xeiam.xchange.poloniex.PoloniexAuthenticated
do not declare throws PoloniexException or IOException

`Caused by: java.lang.reflect.UndeclaredThrowableException: null
    at com.sun.proxy.$Proxy100.returnCompleteBalances(Unknown Source) ~[na:na]
    at com.xeiam.xchange.poloniex.service.polling.PoloniexAccountServiceRaw.getWallets(PoloniexAccountServiceRaw.java:32) ~[xchange-poloniex-4.0.0-SNAPSHOT.jar!/:na]
    at com.xeiam.xchange.poloniex.service.polling.PoloniexAccountService.getAccountInfo(PoloniexAccountService.java:34) ~[xchange-poloniex-4.0.0-SNAPSHOT.jar!/:na]
    ... XXX common frames omitted
Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 522
    at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106) ~[rescu-1.8.1.jar!/:na]
    at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:163) ~[rescu-1.8.1.jar!/:na]
    at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:151) ~[rescu-1.8.1.jar!/:na]
    at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:114) ~[rescu-1.8.1.jar!/:na]
    ... 17 common frames omitted`

**Comment by timmolter** [comment] 2016-03-16 07:55
I'm not sure what's going on. It's likely that the code just needs to be updated to match changes that occurred at Poloniex. You might have to roll up your sleeves and clean up the code!

**Comment by abelgo** [comment] 2016-04-10 06:38
So this kind of stuff happens all the time. These exchanges are not really at any kind of NYSE type professional level. The HTTP 522 error is a connection timeout. It could be any thing from the result of cloud fare blocking a DOS attack, or just some maintenance update where they took the service down.

**Comment by mmazi** [comment] 2016-05-03 10:09
HTTP 522 response code indicates a networking error so this is not an XChange issue.

Even though the handling of this error in XChange is not perfect, XChange did report the relevant error (522), so I guess it did its job. Closing.

**Closed by mmazi** 2016-05-03 10:09 UTC

**Comment by yarKH** [comment] 2016-12-14 13:07
Hi!
Won't open new issue. My question is about UndeclaredThrowableException.
Method declarations:
PoloniexExchange.remoteInit() throws IOException
PoloniexMarketDataServiceRaw.getPoloniexCurrencyInfo() throws IOException
Poloniex.getCurrencyInfo(...) throws PoloniexException, IOException;

Why do I get UndeclaredThrowableException for HttpStatusIOException? I cant catch it with IOException..

StackTrace:

java.lang.RuntimeException: 
...
Caused by: java.lang.reflect.UndeclaredThrowableException
at $Proxy16.getCurrencyInfo(Unknown Source)
at org.knowm.xchange.poloniex.service.polling.PoloniexMarketDataServiceRaw.java.util.Map getPoloniexCurrencyInfo()(ProGuard:35)
at org.knowm.xchange.poloniex.PoloniexExchange.void remoteInit()
...
Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 403
at si.mazi.rescu.ResponseReader.java.lang.Object read(si.mazi.rescu.InvocationResult,si.mazi.rescu.RestMethodMetadata)(ProGuard:106)
java.lang.Object read(java.lang.String,java.lang.reflect.Type)

**Comment by mmazi** [comment] 2016-12-14 13:30
@yarKH I suspect this could be a ProGuard issue. Can you try without ProGuard and see if this still happens? Or perhaps (wildly guessing) ProGuard can be configured to not erase exception information or something?

BTW this is not related to the OP issue so it should probably be opened as a separate issue anyway :)

**Comment by yarKH** [comment] 2016-12-14 13:53
@mmazi thank you! I will try to reproduce without proguard.
Opened new issue and added proguard config.
