### ISSUE TITLE
getExchangeSymbols removed

### ISSUE THREAD

**Issue by Achterhoeker** [timmolter/XChange#1240] opened 2016-04-19 06:33 UTC
In my latest pull from xchange the getExchangeSymbols call is removed.
This api call was for some time marked as deprecated. Advised was to use getMetaData().getMarketMetaDataMap().keySet().

But this call isn't working correctly on some xchanges. For example bter and bittrex are now broken. I can not find any way to acquire the symbol pairs on the common api supported on those exchanges. The getMarketMetaDataMap isn't working on those exchanges. 

How should i now acquire the supported symbol pairs for an exchange ?

**Comment by mmazi** [comment] 2016-05-03 09:51
> The getMarketMetaDataMap isn't working on those exchanges.

Can you elaborate a bit? What's the exception / error message / what does the method return etc.?

**Comment by Achterhoeker** [comment] 2016-05-03 14:18
@mmazi 
Using the old removed function getExchangeSymbols  gives:
Pairs on:Bter :[TIPS/LTC, NAS/BTC, RED/LTC, BQC/CNY, EXC/BTC, FRSH/BTC, TBC/BTC, MGW/BTC, NMC/CNY, BTS/USD, QORA/BTC, RED/CNY, YAC/BTC, C2/BTC, TIPS/CNY, BTCD/NXT, XCP/CNY, QRK/CNY, XCR/BTC, CDC/BTC, VIA/BTC, NXT/USD, BTCD/BTC, XPM/BTC, ETH/BTC, TAG/BTC, NFD/BTC, ARCH/BTC, NET/BTC, UNITY/CNY, CENT/LTC, MINT/BTC, PTS/CNY, DOGE/CNY, DICE/BTC, ZET/CNY, XTC/BTC, UNITY/NXT, DASH/BTC, MMC/BTC, ROX/BTC, LTC/BTC, NXT/CNY, ZCC/BTC, DICE/NXT, NBT/CNY, DOGE/BTC, MMC/CNY, TAG/CNY, MSC/BTC, VTC/BTC, XC/BTC, CENT/CNY, YAC/CNY, NTX/BTC, XMR/CNY, NXTTY/CNY, VRC/BTC, DTC/BTC, GML/BTC, DVC/LTC, NSR/BTC, MEC/BTC, DTC/CNY, NBT/BTC, XEM/BTC, BTC/CNY, FRC/CNY, WDC/CNY, XMR/BTC, DVC/CNY, SFR/BTC, DASH/USD, MEC/CNY, NXTTY/BTC, DGC/CNY, PPC/BTC, CMC/BTC, BBR/BTC, BTB/CNY, PTS/BTC, CKC/BTC, TOKEN/NXT, PPC/CNY, DGC/BTC, XTC/CNY, CNC/BTC, TOKEN/BTCD, VRC/CNY, AC/BTC, DNS/BTC, FLT/BTC, DOGE/USD, ATOMIC/BTC, XPM/CNY, GHOST/BTC, TIX/LTC, SPARK/BTC, BAY/BTC, BITGLD/BTC, MINT/CNY, VTC/CNY, NAV/BTC, BUK/BTC, ETH/CNY, FRC/BTC, PRT/BTC, WDC/BTC, EXC/CNY, NET/LTC, TIX/CNY, BTQ/CNY, SHELL/CNY, KDC/BTC, LTC/CNY, GEMZ/BTC, XCN/BTC, BTS/CNY, NXT/BTC, TBC/CNY, QRK/BTC, MAX/BTC, BTC/BITUSD, IFC/LTC, NMC/BTC, ZCC/CNY, XCP/BTC, BTS/NXT, NET/CNY, BITUSD/USD, BITCNY/CNY, SLM/BTC, XCP/NXT, LTC/USD, BLK/CNY, BLOCK/BTC, FTC/CNY, MAX/CNY, SWIFT/BTC, NODE/BTC, CNC/CNY, TOKEN/CNY, BTC/USD, COMM/BTC, ZET/BTC, DASH/CNY, BTS/BTC, UNITY/BTC, IFC/CNY, FTC/BTC, XCP/USD, MRKT/BTC, NFD/LTC, CMC/CNY, BTB/BTC, NEC/BTC, SRC/CNY, SRC/BTC, AUR/BTC, BLK/BTC, DRKC/BTC, XCH/BTC, LTS/BTC, TOKEN/BTC, BQC/BTC]

Pairs on:Bittrx :[LTC/BTC, DOGE/BTC, VTC/BTC, PPC/BTC, FTC/BTC, RDD/BTC, NXT/BTC, DASH/BTC, POT/BTC, BLK/BTC, EMC2/BTC, MYR/BTC, AUR/BTC, UTC/BTC, MZC/BTC, EFL/BTC, SLR/BTC, PTC/BTC, GRS/BTC, NLG/BTC, RBY/BTC, XWC/BTC, MONA/BTC, BITS/BTC, OC/BTC, THC/BTC, ENRG/BTC, SFR/BTC, ERC/BTC, NAUT/BTC, VRC/BTC, CURE/BTC, URO/BTC, BLC/BTC, XC/BTC, XDQ/BTC, BBR/BTC, HYPER/BTC, CCN/BTC, XMR/BTC, CLOAK/BTC, CRYPT/BTC, START/BTC, KORE/BTC, XDN/BTC, TRK/BTC, QTL/BTC, TRUST/BTC, NAV/BTC, XST/BTC, APEX/BTC, BTCD/BTC, VIA/BTC, TRI/BTC, UNO/BTC, PINK/BTC, IOC/BTC, SDC/BTC, MAX/BTC, LXC/BTC, BOB/BTC, MWC/BTC, CANN/BTC, FC2/BTC, SSD/BTC, J/BTC, SYS/BTC, NEOS/BTC, DGB/BTC, ROOT/BTC, FIBRE/BTC, JBS/BTC, TIT/BTC, BSTY/BTC, BURST/BTC, PXI/BTC, DGC/BTC, SLG/BTC, ROS/BTC, STV/BTC, EXCL/BTC, SWIFT/BTC, ARCH/BTC, NET/BTC, GAIA/BTC, GHC/BTC, MARYJ/BTC, DOPE/BTC, SMBR/BTC, BLOCK/BTC, ABY/BTC, QSLV/BTC, VIOR/BTC, BYC/BTC, UFO/BTC, XMG/BTC, XQN/BTC, BLITZ/BTC, VPN/BTC, BAY/BTC, DTC/BTC, BTS/BTC, AM/BTC, FAIR/BTC, METAL/BTC, SPR/BTC, VTR/BTC, XPY/BTC, XAI/BTC, XRP/BTC, GAME/BTC, BCR/BTC, GP/BTC, RBR/BTC, FSC2/BTC, NIRO/BTC, SOON/BTC, XCP/BTC, SJCX/BTC, BITB/BTC, XTC/BTC, HZ/BTC, GEO/BTC, FLDC/BTC, WBB/BTC, GEMZ/BTC, GRC/BTC, XCO/BTC, MTR/BTC, FLO/BTC, U/BTC, NBT/BTC, MUE/BTC, XEM/BTC, TRON/BTC, 8BIT/BTC, CLAM/BTC, XSEED/BTC, NTRN/BTC, SLING/BTC, IEC/BTC, DMD/BTC, GAM/BTC, UNIT/BTC, GRT/BTC, VIRAL/BTC, SPHR/BTC, ARB/BTC, OK/BTC, ADC/BTC, SNRG/BTC, PKB/BTC, TES/BTC, DIGS/BTC, CPC/BTC, BITZ/BTC, AEON/BTC, ETH/BTC, GCR/BTC, TX/BTC, SHF/BTC, BCY/BTC, PRIME/BTC, EXP/BTC, NEU/BTC, SWING/BTC, MAPC/BTC, INFX/BTC, SOIL/BTC, OMNI/BTC, AMP/BTC, AGRS/BTC, SPRTS/BTC, YBC/BTC, XLM/BTC, BTA/BTC, MEC/BTC, CUBE/BTC, AMS/BTC, BTC/USDT, BTC/BITCNY, SCRT/BTC, SCOT/BTC, CLUB/BTC, BNT/BTC, VOX/BTC, MND/BTC, EMC/BTC, FCT/BTC, MAID/BTC, FRK/BTC, EGC/BTC, SLS/BTC, HIRE/BTC, ORB/BTC, STEPS/BTC, RADS/BTC, DCR/BTC, SEC/BTC, BSD/BTC, XVG/BTC, DNET/BTC, WARP/BTC, CRBIT/BTC, XVC/BTC, MEME/BTC, DES/BTC, SAR/BTC, STEEM/BTC]


Using the new supposed function getMetaData().getMarketMetaDataMap().keySet() : 
Pairs on Bter: [BTC/CNY, LTC/CNY]
Pairs on Bittrex: [LTC/BTC]

As you can see, almost all markets are missing with the getMetaData call. Remote init doesn't fill them as they should do. (the old function getExchangeSymbols  was giving all markets as reported by the remote api)

So I can not acquire all market pairs without getExchangeSymbols on the current build on the common api.

**Comment by mmazi** [comment] 2016-05-03 18:06
@rafalkrupinski Any idea?

**Comment by rafalkrupinski** [comment] 2016-05-04 10:42
It appears that getMarketMetaDataMap() returns only what's declared in the json files, so either remoteInit() is unimplemented or implemented incorrectly or it's simply not called. I can look into it later today.

**Comment by zholmes1** [comment] 2016-06-20 14:49
The problem is that polling services don't extend BaseExchangeService, which is what contains the getExchangeSymbols() method.

I am having the same issue. I can no longer call getExchangeSymbols() from my PollingMarketDataService. Getting the meta data doesn't work because (at least for some exchange) it does not contain the same functionality. For instance, for Poloniex it only returns one pair (BTC/USD) which obviously is incorrect. Currently there's no way to get to the correct exchange symbols except for getting the raw services.

I'm not 100% sure but I think that this could be fixed by adding getExchangeSymbols() to BasePollingService.

**Comment by Achterhoeker** [comment] 2016-06-21 07:17
Zach, polo is working fine here, but you need to call remoteInit() after
creating the exchange. That will fill the meta data with the symbols
retrieved from the remote exchange.

Ronald

Op 20-6-2016 om 16:50 schreef Zach Holmes:

**Comment by timmolter** [comment] 2016-06-21 14:07
Please see: Exchange Metadata Update and Discussion #1282

**Comment by Achterhoeker** [comment] 2016-06-23 09:07
@timmolter 
This ticket seems to be closed. But there is still no way to get the exchange symbols on bittrex and bter. So i'm stuck to an old version were a working getExchangeSymbols  is still present.

**Comment by timmolter** [comment] 2016-06-23 12:35
OK, I implemented it for Bter. See `BTERExchangeDemo`. Notice the coding I did in `BTERExchange`.

**Comment by timmolter** [comment] 2016-10-14 11:42
`getExchangeSymbols` is working now.

**Closed by timmolter** 2016-10-14 11:42 UTC
