### ISSUE TITLE
PoloniexTradeService.getTradeHistory deserialize problem on empty trade history

### ISSUE THREAD

**Issue by abelgo** [timmolter/XChange#1167] opened 2016-01-15 15:40 UTC
From my reading of the API, I am expecting the get a null return from getTradeHistory however I am hitting this Exception I'm not sure exactly how best to deal with.

SEVERE: POLX-T Executions Pole 0 Exception in account pole Can not deserialize instance of java.util.HashMap out of START_ARRAY token
 at [Source: []; line: 1, column: 1]
si.mazi.rescu.HttpStatusIOException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token
 at [Source: []; line: 1, column: 1]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104)
	at com.sun.proxy.$Proxy13.returnTradeHistory(Unknown Source)
	at com.xeiam.xchange.poloniex.service.polling.PoloniexTradeServiceRaw.returnTradeHistory(PoloniexTradeServiceRaw.java:48)
	at com.xeiam.xchange.poloniex.service.polling.PoloniexTradeService.getTradeHistory(PoloniexTradeService.java:128)
	at com.xeiam.xchange.poloniex.service.polling.PoloniexTradeService.getTradeHistory(PoloniexTradeService.java:121)

**Comment by abelgo** [comment] 2016-01-17 03:54
I've been trying with out any success to get logging switched on in si.mazi.rescu so I can see the actual HTTP request output. However no amount of adding logback config files to the class path has any impact at all on the logging. I'm starting to wonder if this has ever worked correctly as I don't see it in the past release

**Comment by timmolter** [comment] 2016-01-18 11:46
See <https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices> for how to get the raw TRACE and DEBUG logs into the console. Instead of hours, it will take a few seconds. It should definitely work.

**Comment by timmolter** [comment] 2016-01-18 11:46
Are you sure it's on the classpath? Are you using Maven?

**Comment by mmazi** [comment] 2016-01-18 11:47
Sorry to see this is taking a lot of your time and energy. I'll try to find some time to help you get this working today and tomorrow; I'm rather busy though so please bear with me.

Re. the logging issue, just adding (or uncommenting) this line in `xchange-examples/.../logback.xml` did the trick for me when running eg. `PoloniexMarketDataDemo`:

    <logger name="si.mazi.rescu" level="TRACE" />

Rescu then logs the complete request data and returned json. The actual file where you need to do this depends a bit on your setup.

As for the main issue, the issue is actually that the Poloniex server (incorrectly) returns an empty array json [] instead of a empty map json {}. We need a good way to deal with this in XChange though (or perhaps in rescu) because I think I've seen this issue before, so it seems some servers just do this regularly.

**Comment by mmazi** [comment] 2016-01-18 13:16
The Jackson feature `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` seems to be just what you need:

> Feature that can be enabled to allow empty JSON Array value (that is, [ ]) to be bound to POJOs as null. If disabled, standard POJOs can only be bound from JSON null or JSON Object (standard meaning that no custom deserializers or constructors are defined; both of which can add support for other kinds of JSON values); if enabled, empty JSON Array will be taken to be equivalent of JSON null.

Use it like this in `PoloniexBasePollingService`:

        ClientConfig config = new ClientConfig();
        config.setJacksonConfigureListener(
                new JacksonConfigureListener() {
                    @Override
                    public void configureObjectMapper(ObjectMapper objectMapper) {
                        objectMapper.configure(DeserializationFeature. ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
                    }
                }
        );

        this.poloniexAuthenticated = RestProxyFactory.createProxy(PoloniexAuthenticated.class, exchange.getExchangeSpecification().getSslUri(), config);

Please let me know if this helps solve the issue, or if you need further help with implementing this.

**Comment by abelgo** [comment] 2016-01-18 13:39
@timmolter  Re: adding logback.xml  with trace option to classpath. 
Yes I use Maven,  I have the logback.xml file in the Maven src/main/resource folder and also tried putting it in the default package can even trying to add it on the -cp switch,  But no luck at all. There are other dependencies in my project pom that use things like slf4j-simple. I'm not that familiar with log4j as I usually just use the basic java logger.  There must just be something I am totally missing here.

**Comment by abelgo** [comment] 2016-01-18 13:45
@mmazi  ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT  looks like exactly what we need. Sorry I wasn't quite familiar enough with XChange to know where and how best to do that. Saw the annotations on the POJOs but haven't fully understood the rest of the code base yet.. Want to try and use it correctly first before I start trying to change it.

**Comment by mmazi** [comment] 2016-01-18 14:25
Logging: you need to add the correct logging *dependency* in the classpath, not just the `logback.xml` file. Logback is only one of the possible implementations for slf4j. Another is lsf4j-simple, but I think this only gets used if no other implementations are present. If this is so, just adding the logback dependency should do the trick:

http://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.1.3

Also, you are mentioning log4j, but you probably meant slf4j (this is something different)? If your project is already using log4j, you should configure the logging levels through log4j's mechanisms (eg. log4j.properties), not Logback's (logback.xml).

Also, please check what slf4j logs in the error output at application startup. It should log which implementation it is using and if there are any conflicts. This should shed some light on the issue.

**Comment by abelgo** [comment] 2016-01-18 14:57
Brilliant !!!! that actually worked... 
2015 and its already a classic ?? ;-)
So I added the log4j.properties previously to deal with the included jars using that.

    log4j.rootLogger=info, console
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n
    log4j.logger.si.mazi.rescu=trace

Then the added the logback clasic dependency and .... bingo it started logging  !! fantastic.. 
   <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.12</version>
        </dependency>

**Comment by mmazi** [comment] 2016-01-18 15:09
Logging: um, you should use either logback or log4j, not both... But anyway, happy to hear that logging works now.

**Comment by mmazi** [comment] 2016-01-25 07:20
@abelgo , did `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` work for you? Is this issue resolved, can it be closed?

**Comment by abelgo** [comment] 2016-01-25 07:44
Yes. Worked.  I haven't checked any of the code back in or merged it so its still a problem in the dev branch.  There is also another hack I put in my branch, to deal with the getTicker(currency_code) call in the API.  Basically the poloiex Exchange API returns all ticker data in one call. then getTicker(currency_code) just pulls the selected ticker out of the hash map. This is pretty wasteful if you are calling getTicker in a for loop with the 20+ different alt coins they support your making 20 HTTPS calls to get the same data set thats cashed on the exchange side any how especially since the hash map lookup is happening in microseconds where as each https call can take several seconds at times,   

So not sure my hack code is going to be quite up to the standard of the project I can commit the branch if you like don't know how you guy would deal with the second problem.  I just cache the returned HashMap for a second before making another HTTP call in my version of the API

**Comment by mmazi** [comment] 2016-01-25 08:31
Can you just make a pull request with the array deserialization fix (`ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT`), and not the ticker fix?

If you can't do that, then it's ok if you make a pull request for both and I'll separate them.

**Comment by timmolter** [comment] 2016-01-25 08:36
I think the second "hack" is actually OK. I did something similar once in another module.

**Comment by mmazi** [comment] 2016-05-03 10:22
I see both `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` and the ticker cache hack have been added  by 948eb1aff. Closing this issue.

I'll implement general support for the caching issue in rescu:
https://github.com/mmazi/rescu/issues/80

I'll might replace the custom hack for Poloniex with the new rescu's `@Cached` when implemented.

**Closed by mmazi** 2016-05-03 10:22 UTC
Labels: Question
